# Generated by Django 4.0.4 on 2022-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizzes',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='question',
            name='technique',
            field=models.IntegerField(default=0, verbose_name='Type of Question'),
        ),
    ]
