# Generated by Django 4.0.4 on 2022-05-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_answer_category_profile_question_result_resulttests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='IsRight',
            new_name='is_right',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='QuestionId',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Good',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Perfect',
            new_name='perfect',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='QuestionsCount',
            new_name='questions_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Statisfactorily',
            new_name='statisfactorily',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='WorkTime',
            new_name='work_time',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ProfileId',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='DateTime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='ProfileId',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='UserName',
            new_name='username',
        ),
    ]
